# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5c2cc13f59d6bde01513ee24af2c1b04cf6aa328892b1a5e67af2aeeb76ba52f033ac65e1cb898d780cc163d02996e5107b5c60c6c66a73eb28d0d6245150ca

test:
  secret_key_base: 737e4956cf90746dedc08d0c0fe8b92810d9cb1edd250938a75bd0012bb8cf863575c64c53af39002e1afa4526fbe0396ce770024bde4ce3a7f4396bd9b58de3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
